language: node_js
node_js:
  - "node"
before_deploy: ls -A | grep -v -e 'dist' -e 'assets' | xargs rm -r && cp -r dist/* . && rm -r dist
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in the settings page of your repository, as a secure variable
  on:
    branch: master
