language: node_js
node_js:
  - "node"
before_deploy: find . | grep -v 'dist' | xargs rm && cp -r dist/* . && rm -r dist
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in the settings page of your repository, as a secure variable
  on:
    branch: master
